travis:
  secure:
    BINSTAR_TOKEN: hJhpqDI+r/b1cgw+a49/qnZ5miqKnl/ukpvTvCmWdP6c3wv2GFGyj8496As2s4kSIZ2SkL5cFxqltZo/RKTHA1Cy2ZqDXNJhfMIfyqnvxAYqMEEQb03nZRrgtLUH+XvGlggJDI8z+oD8WVhd2zRUkDfR3rqZsLemjLpNe1WKM9HwvWoEUAfxicqG+1f2ppLMFb/2LO2U5WtdzXFdHNyu/sMjpVlhAFqy2YzETlk6jdcK+AZqwGKslFoDGutpeJX/n3IG8pdnzuxJYZvGNjpW5u5QCS7Lrkm+G1BgNntl5oS7SBy5WpBN/Pnv9RiB5XIl5HogNJbiT6LuLaO+OxCYsCWFxt/or78lTuV89CproRg3RQuUKZj38XyHgy2a1lo66FmExt40eDn70LPHbVh6VXTFa/uURT8eGqrhczo5P0HC63jRW0CjxVuovxf2Xlj89302xCwynT5QQ3Qcd3kb05JptvRd7St4FvLkdZSax3pJTE6sRV/dmesxAzR/dVcVjqbryiqXNHeTaELySLEdegp1rDeNvzVQWh2POJC9ODwF41m27L6ztA7u6lILjbaOv+zkN9fYSupLkjmXq64n8Z+kj7sFy38XIlb+BU7D/T1rOwsKi8MoLCDSgWvUIZP7cBdO1Pqyvak1qOTUmnFbAmeT3d0cnQQl9GMD6pBk3H8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
